In [2]:
import numpy as np
import pandas as pd
np.random.seed(100)

sales_amounts = np.random.randint(10,size = (5,5))

In [3]:
sales_amounts

array([[8, 8, 3, 7, 7],
       [0, 4, 2, 5, 2],
       [2, 2, 1, 0, 8],
       [4, 0, 9, 6, 2],
       [4, 1, 5, 3, 4]])

In [8]:
weekly_sales = pd.DataFrame(sales_amounts,index= ["Mon","Tues","Wed","Thurs","Fri"],
                            columns=["GPU",'PC','CPU',"Phone","Mouse"])
weekly_sales

GPU  PC  CPU  Phone  Mouse
Mon      8   8    3      7      7
Tues     0   4    2      5      2
Wed      2   2    1      0      8
Thurs    4   0    9      6      2
Fri      4   1    5      3      4

In [14]:
prices = np.array([100,200,300,500,299])
prices.shape

(5,)

In [15]:
electronic_prices = pd.DataFrame(prices.reshape(1,5),index = ['Prices'],
                                 columns = ["GPU",'PC','CPU',"Phone","Mouse"])
electronic_prices

GPU   PC  CPU  Phone  Mouse
Prices  100  200  300    500    299

In [24]:
total_sales = sales_amounts.dot(electronic_prices.T)
total_sales

array([[8893],
       [4498],
       [3292],
       [6698],
       [4796]])

In [25]:
total_sales.T

array([[8893, 4498, 3292, 6698, 4796]])

In [31]:
daily_sales = electronic_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues   Wed  Thurs   Fri
Prices  8893  4498  3292   6698  4796

In [33]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

GPU  PC  CPU  Phone  Mouse  Total ($)
Mon      8   8    3      7      7       8893
Tues     0   4    2      5      2       4498
Wed      2   2    1      0      8       3292
Thurs    4   0    9      6      2       6698
Fri      4   1    5      3      4       4796

In [34]:
import numpy as np

In [36]:
one_d_array = np.array([1,2,3])

In [37]:
two_d_array = np.array([[1,2,3,4],
                        [5,6,7,3]])

In [43]:
three_d_array = np.array([[[1,2,3,4],
                           [5,6,3,5],
                           [3,4,5,6]]])

In [46]:
one_d_array.shape,one_d_array.ndim,one_d_array.dtype,one_d_array.size,type(one_d_array)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [47]:
two_d_array.shape,two_d_array.ndim,two_d_array.dtype,two_d_array.size,type(two_d_array)

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

In [48]:
three_d_array.shape,three_d_array.ndim,three_d_array.dtype,three_d_array.size,type(three_d_array)

((1, 3, 4), 3, dtype('int32'), 12, numpy.ndarray)

In [54]:
import pandas as pd
df1 = pd.DataFrame(one_d_array)
df1

0
0  1
1  2
2  3

In [57]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
array_step_three = np.arange(0,100,3)
array_step_three

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [66]:
random_array = np.random.randint(10,size = (7,2))
random_array

array([[8, 1],
       [0, 7],
       [6, 2],
       [0, 8],
       [2, 5],
       [1, 8],
       [1, 5]])

In [69]:

random_array_float = np.random.random(size=(3,5))
random_array_float

array([[0.64027806, 0.62477951, 0.14550751, 0.5702159 , 0.0651125 ],
       [0.31341257, 0.21706577, 0.52695039, 0.42710838, 0.98263043],
       [0.14045149, 0.7484116 , 0.78884039, 0.73039662, 0.84561834]])

In [72]:
np.random.seed(42)
random_array_numbers = np.random.randint(10 , size = (4,6))
random_array_numbers

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [76]:
array = np.random.randint(10,size=(3,7))
array
np.unique(array)

array([0, 1, 2, 4, 6, 7, 8, 9])

In [80]:
array[:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [85]:
rand_arr = np.random.randint(10,size = (3,5))
ones1 = np.ones((3,5))

In [86]:
rand_arr + ones1

array([[ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.],
       [ 4.,  9.,  3.,  7.,  6.]])

In [87]:
another_array = np.ones((5,3))

In [100]:
results_array = rand_arr + ones1 + another_array.T

In [93]:
ones2 = np.ones((3,5))
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
ones2 - another_array.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
ones2 * another_array.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
ones2 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
np.square(ones2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
np.mean(ones2)

1.0

In [101]:
np.max(results_array)

11.0

In [102]:
results_array

array([[ 7.,  5., 11.,  8., 10.],
       [ 8.,  2.,  2., 10., 10.],
       [ 5., 10.,  4.,  8.,  7.]])

In [103]:
np.min(results_array)

2.0

In [104]:
np.std(results_array)

2.8487814158961995

In [106]:
np.var(results_array)

8.115555555555554

In [107]:
results_array.reshape(3,5,1)

array([[[ 7.],
        [ 5.],
        [11.],
        [ 8.],
        [10.]],

       [[ 8.],
        [ 2.],
        [ 2.],
        [10.],
        [10.]],

       [[ 5.],
        [10.],
        [ 4.],
        [ 8.],
        [ 7.]]])

In [108]:
results_array.T

array([[ 7.,  8.,  5.],
       [ 5.,  2., 10.],
       [11.,  2.,  4.],
       [ 8., 10.,  8.],
       [10., 10.,  7.]])

In [110]:
array1 = np.random.randint(10,size = (3,3))
array2 = np.random.randint(10,size = (3,2))

In [111]:
array1.dot(array2)

array([[ 0, 53],
       [ 0, 63],
       [ 0, 31]])

In [112]:
array3 = np.random.randint(10,size = (4,3))
array4 = np.random.randint(10,size = (4,3))

In [114]:
array3.dot(array4.T)

array([[39, 32, 26, 31],
       [48, 42, 58, 26],
       [12,  5, 11, 15],
       [81, 53, 79, 74]])

In [115]:
array5 = np.random.randint(10,size = (3,3))
array6 = np.random.randint(10,size = (3,3))

In [116]:
array5 > array6

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

In [117]:
array5 >= array6

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

In [118]:
array1 > 7

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [119]:
array1

array([[8, 3, 0],
       [0, 9, 3],
       [6, 1, 2]])

In [122]:
array3 == array4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [123]:
np.sort(array3)

array([[1, 1, 5],
       [0, 4, 6],
       [0, 1, 2],
       [4, 5, 9]])

In [124]:
np.argsort(array3)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [125]:
np.argmax(array3)

10

In [126]:
array3

array([[1, 1, 5],
       [6, 4, 0],
       [0, 2, 1],
       [4, 9, 5]])

In [127]:
np.argmin(array3)

5

In [128]:
np.argmax(array3,axis =1)

array([2, 0, 1, 1], dtype=int64)

In [129]:
np.argmin(array3,axis = 0)

array([2, 0, 1], dtype=int64)

In [130]:
np.random.randn(3,5)

array([[ 0.48197914,  0.92645636, -0.83758139,  0.67718607,  1.87231912],
       [ 0.39637394, -0.6256163 , -0.52246148,  0.0130339 ,  0.37776959],
       [ 0.0628246 ,  0.50159637, -0.14694539,  0.18062297,  0.96481058]])

In [132]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])